<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;
use App\Models\Category;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoryMap = [
            'Fiksi' => 1,
            'Fiksi Sejarah' => 7,
            'Non-Fiksi' => 2,
            'Pengembangan Diri' => 4,
            'Fiksi Sains' => 6,
            'Sains Fiksi' => 6,
            'Komputer' => 3,
            'Perpustakaan' => 5,
            'Sejarah' => 7,
        ];

        $books = [
            [
                'title' => 'Laskar Pelangi',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'year' => 2005,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 5,
            ],
            [
                'title' => 'Bumi Manusia',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Lentera Dipantara',
                'year' => 1980,
                'id_kategori' => $categoryMap['Fiksi Sejarah'],
                'stock' => 3,
            ],
            [
                'title' => 'Sapiens: A Brief History of Humankind',
                'author' => 'Yuval Noah Harari',
                'publisher' => 'Pustaka Al Kautsar',
                'year' => 2014,
                'id_kategori' => $categoryMap['Non-Fiksi'],
                'stock' => 4,
            ],
            [
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'publisher' => 'Penerbit Bentang',
                'year' => 2018,
                'id_kategori' => $categoryMap['Pengembangan Diri'],
                'stock' => 6,
            ],
            [
                'title' => 'Dune',
                'author' => 'Frank Herbert',
                'publisher' => 'Ace Books',
                'year' => 1965,
                'id_kategori' => $categoryMap['Sains Fiksi'],
                'stock' => 2,
            ],
            [
                'title' => 'Algoritma Pemrograman',
                'author' => 'Ir. Napsiah, MT',
                'publisher' => 'Andi',
                'year' => 2019,
                'id_kategori' => $categoryMap['Komputer'],
                'stock' => 7,
            ],
            [
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'publisher' => 'Prentice Hall',
                'year' => 2008,
                'id_kategori' => $categoryMap['Komputer'],
                'stock' => 4,
            ],
            [
                'title' => 'Manajemen Perpustakaan',
                'author' => 'Dr. Hj. Sumiati, M.Pd',
                'publisher' => 'Deepublish',
                'year' => 2022,
                'id_kategori' => $categoryMap['Perpustakaan'],
                'stock' => 5,
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'publisher' => 'Secker & Warburg',
                'year' => 1949,
                'id_kategori' => $categoryMap['Sains Fiksi'],
                'stock' => 8,
            ],
            [
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'publisher' => 'HarperOne',
                'year' => 1988,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 6,
            ],
            [
                'title' => 'Habis Gelap Terbitlah Terang',
                'author' => 'Soekarno',
                'publisher' => 'Penerbit Ombak',
                'year' => 2010,
                'id_kategori' => $categoryMap['Sejarah'],
                'stock' => 5,
            ],
            [
                'title' => 'Laut Bercerita',
                'author' => 'Leila S. Chudori',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2017,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 4,
            ],
            [
                'title' => 'Gadis Kretek',
                'author' => 'Ratih Kumala',
                'publisher' => 'Gramedia',
                'year' => 2009,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 3,
            ],
            [
                'title' => 'Perahu Kertas',
                'author' => 'Dee Lestari',
                'publisher' => 'GagasMedia',
                'year' => 2006,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 5,
            ],
            [
                'title' => 'Ranah 3 Warna',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Gramedia',
                'year' => 2011,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 6,
            ],
            [
                'title' => 'Sang Pemimpi',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Bentang Pustaka',
                'year' => 2006,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 5,
            ],
            [
                'title' => 'Edensor',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Bentang Pustaka',
                'year' => 2007,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 4,
            ],
            [
                'title' => 'Guru Aini',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Gadu Media',
                'year' => 2013,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 3,
            ],
            [
                'title' => 'Ronggeng Dukuh Paruk',
                'author' => 'Ahmad Tohari',
                'publisher' => 'Gramedia',
                'year' => 1982,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 4,
            ],
            [
                'title' => 'Orang-Orang Proyek',
                'author' => 'Ahmad Tohari',
                'publisher' => 'Hasta Mitra',
                'year' => 1990,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 3,
            ],
            [
                'title' => 'Di Timur Matahari',
                'author' => 'Oriza Saleh Lubis',
                'publisher' => 'Gramedia',
                'year' => 2003,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 5,
            ],
            [
                'title' => 'Amba',
                'author' => 'Laksmi Pamuntjak',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2012,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 6,
            ],
            [
                'title' => 'Animal Farm',
                'author' => 'George Orwell',
                'publisher' => 'Harcourt Brace',
                'year' => 1945,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 5,
            ],
            [
                'title' => 'The Little Prince',
                'author' => 'Antoine de Saint-Exupéry',
                'publisher' => 'Reynal & Hitchcock',
                'year' => 1943,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 7,
            ],
            [
                'title' => 'Harry Potter and the Philosopher\'s Stone',
                'author' => 'J.K. Rowling',
                'publisher' => 'Bloomsbury',
                'year' => 1997,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 8,
            ],
            [
                'title' => 'Harry Potter and the Chamber of Secrets',
                'author' => 'J.K. Rowling',
                'publisher' => 'Bloomsbury',
                'year' => 1998,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 6,
            ],
            [
                'title' => 'Harry Potter and the Prisoner of Azkaban',
                'author' => 'J.K. Rowling',
                'publisher' => 'Bloomsbury',
                'year' => 1999,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 5,
            ],
            [
                'title' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'publisher' => 'George Allen & Unwin',
                'year' => 1937,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 4,
            ],
            [
                'title' => 'The Fellowship of the Ring',
                'author' => 'J.R.R. Tolkien',
                'publisher' => 'Allen & Unwin',
                'year' => 1954,
                'id_kategori' => $categoryMap['Fiksi'],
                'stock' => 6,
            ],
            [
                'title' => 'Rich Dad Poor Dad',
                'author' => 'Robert T. Kiyosaki',
                'publisher' => 'Plata Publishing',
                'year' => 1997,
                'id_kategori' => $categoryMap['Pengembangan Diri'],
                'stock' => 7,
            ],
            [
                'title' => 'Think and Grow Rich',
                'author' => 'Napoleon Hill',
                'publisher' => 'The Ralston Society',
                'year' => 1937,
                'id_kategori' => $categoryMap['Pengembangan Diri'],
                'stock' => 8,
            ],
            [
                'title' => 'How to Win Friends and Influence People',
                'author' => 'Dale Carnegie',
                'publisher' => 'Simon & Schuster',
                'year' => 1936,
                'id_kategori' => $categoryMap['Pengembangan Diri'],
                'stock' => 6,
            ],
            [
                'title' => 'The 7 Habits of Highly Effective People',
                'author' => 'Stephen R. Covey',
                'publisher' => 'Free Press',
                'year' => 1989,
                'id_kategori' => $categoryMap['Pengembangan Diri'],
                'stock' => 5,
            ],
            [
                'title' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'publisher' => 'Farrar, Straus and Giroux',
                'year' => 2011,
                'id_kategori' => $categoryMap['Non-Fiksi'],
                'stock' => 7,
            ],
            [
                'title' => 'Homo Deus',
                'author' => 'Yuval Noah Harari',
                'publisher' => 'Harper',
                'year' => 2016,
                'id_kategori' => $categoryMap['Non-Fiksi'],
                'stock' => 5,
            ],
            [
                'title' => 'The Power of Habit',
                'author' => 'Charles Duhigg',
                'publisher' => 'Random House',
                'year' => 2012,
                'id_kategori' => $categoryMap['Pengembangan Diri'],
                'stock' => 6,
            ],
            [
                'title' => 'Introduction to Algorithms',
                'author' => 'Thomas H. Cormen',
                'publisher' => 'MIT Press',
                'year' => 2009,
                'id_kategori' => $categoryMap['Komputer'],
                'stock' => 8,
            ],
            [
                'title' => 'Design Patterns',
                'author' => 'Erich Gamma',
                'publisher' => 'Addison-Wesley',
                'year' => 1994,
                'id_kategori' => $categoryMap['Komputer'],
                'stock' => 5,
            ],
            [
                'title' => 'The Pragmatic Programmer',
                'author' => 'Andrew Hunt',
                'publisher' => 'Addison-Wesley',
                'year' => 1999,
                'id_kategori' => $categoryMap['Komputer'],
                'stock' => 6,
            ],
            [
                'title' => 'Refactoring',
                'author' => 'Martin Fowler',
                'publisher' => 'Addison-Wesley',
                'year' => 1999,
                'id_kategori' => $categoryMap['Komputer'],
                'stock' => 4,
            ],
            [
                'title' => 'Cracking the Coding Interview',
                'author' => 'Gayle Laakmann McDowell',
                'publisher' => 'CareerCup',
                'year' => 2015,
                'id_kategori' => $categoryMap['Komputer'],
                'stock' => 9,
            ],
            [
                'title' => 'A Short History of Nearly Everything',
                'author' => 'Bill Bryson',
                'publisher' => 'Broadway Books',
                'year' => 2003,
                'id_kategori' => $categoryMap['Non-Fiksi'],
                'stock' => 6,
            ],
            [
                'title' => 'Guns, Germs, and Steel',
                'author' => 'Jared Diamond',
                'publisher' => 'W.W. Norton',
                'year' => 1997,
                'id_kategori' => $categoryMap['Sejarah'],
                'stock' => 7,
            ],
            [
                'title' => 'The Diary of a Young Girl',
                'author' => 'Anne Frank',
                'publisher' => 'Contact Publishing',
                'year' => 1947,
                'id_kategori' => $categoryMap['Sejarah'],
                'stock' => 4,
            ],
            [
                'title' => 'Quiet',
                'author' => 'Susan Cain',
                'publisher' => 'Crown Publishing',
                'year' => 2012,
                'id_kategori' => $categoryMap['Non-Fiksi'],
                'stock' => 5,
            ],
            [
                'title' => 'Educated',
                'author' => 'Tara Westover',
                'publisher' => 'Random House',
                'year' => 2018,
                'id_kategori' => $categoryMap['Non-Fiksi'],
                'stock' => 6,
            ],
            [
                'title' => 'Becoming',
                'author' => 'Michelle Obama',
                'publisher' => 'Crown',
                'year' => 2018,
                'id_kategori' => $categoryMap['Non-Fiksi'],
                'stock' => 8,
            ],
            [
                'title' => 'Steve Jobs',
                'author' => 'Walter Isaacson',
                'publisher' => 'Simon & Schuster',
                'year' => 2011,
                'id_kategori' => $categoryMap['Non-Fiksi'],
                'stock' => 5,
            ],
            [
                'title' => 'Astrophysics for People in a Hurry',
                'author' => 'Neil deGrasse Tyson',
                'publisher' => 'W.W. Norton',
                'year' => 2017,
                'id_kategori' => $categoryMap['Non-Fiksi'],
                'stock' => 7,
            ],
            [
                'title' => 'Brief Answers to the Big Questions',
                'author' => 'Stephen Hawking',
                'publisher' => 'Bantam Books',
                'year' => 2018,
                'id_kategori' => $categoryMap['Non-Fiksi'],
                'stock' => 6,
            ],
        ];

        foreach ($books as $bookData) {
            Book::updateOrCreate(
                [
                    'title' => $bookData['title'],
                    'author' => $bookData['author']
                ],
                $bookData
            );
        }
    }
}

